// Java language runtime for code generated by src/compiler (DOM-free). Generated code receives `lang`
// as `$rt.lang` and binds the helpers it uses to local constants; library classes are looked up by
// binary name in `$rt.classes` (see javaClasses).
import * as arrays from "./arrays.ts";
import * as boxes from "./boxes.ts";
import * as exceptions from "./exceptions.ts";
import * as functional from "./functional.ts";
import * as jlang from "./jlang.ts";
import * as misc from "./misc.ts";
import * as numbers from "./numbers.ts";
import * as objects from "./objects.ts";
import * as print from "./print.ts";
import * as strings from "./strings.ts";
import * as util from "./util.ts";

export const lang = { ...numbers, ...boxes, ...exceptions, ...objects, ...arrays, ...print, ...misc, S: strings };
export type Lang = typeof lang;

/** Runtime classes of java.* types, by binary name (merged into $rt.classes by the host). */
export const javaClasses: Record<string, unknown> = {
  "java.lang.Integer": jlang.Integer,
  "java.lang.Long": jlang.Long,
  "java.lang.Float": jlang.Float,
  "java.lang.Double": jlang.Double,
  "java.lang.Character": jlang.Character,
  "java.lang.Boolean": jlang.Boolean,
  "java.lang.StringBuilder": jlang.StringBuilder,
  "java.lang.StringBuffer": jlang.StringBuilder,
  "java.util.ArrayList": util.ArrayList,
  "java.util.HashMap": util.HashMap,
  "java.util.HashSet": util.HashSet,
  "java.util.Collections": util.Collections,
  "java.util.Arrays": util.Arrays,
  "java.util.Comparator": functional.Comparator,
  "java.util.function.Function": functional.FunctionStatics,
  "java.util.function.UnaryOperator": functional.FunctionStatics,
  "java.util.function.Predicate": functional.PredicateStatics,
};

export { arrays, boxes, exceptions, functional, jlang, misc, numbers, objects, print, strings, util };
