// Processing's array functions and splitTokens().
int[] a = { 5, 3, 9, 1 };
float[] f = { 2.5, -1, 0.1 };
String[] s = { "pear", "Apple", "fig" };
println(append(a, 7));
println(append(f, 3.25));
String[] s2 = (String[]) append(s, "kiwi");
println(s2);
printArray(subset(a, 1));
printArray(subset(a, 1, 2));
printArray((String[]) subset(s, 2));
printArray(concat(a, new int[] { 4, 4 }));
printArray((String[]) concat(s, new String[] { "x" }));
printArray(expand(a));
println(expand(f, 5).length + " " + expand(s, 1).length);
printArray(reverse(a));
printArray((String[]) reverse(s));
printArray(shorten(a));
printArray(sort(a));
printArray(sort(a, 2));
printArray(sort(f));
printArray(sort(s));
println(a[0] + " " + s[0]);
printArray(splice(a, 42, 1));
printArray(splice(a, new int[] { 7, 8 }, 4));
printArray((String[]) splice(s, "mid", 0));
char[] cs = { 'd', 'a', 'c' };
println(sort(cs));
int[] dst = new int[6];
arrayCopy(a, 1, dst, 2, 3);
printArray(dst);
arrayCopy(a, dst, 2);
printArray(dst);
arrayCopy(a, dst);
printArray(dst);
printArray(splitTokens("a, b,,c  d", ", "));
printArray(splitTokens("  one two\tthree\n"));
println(splitTokens("", ",").length);
