// PVector: float arithmetic, static methods, toString.
PVector a = new PVector(1.1, 2.2, 3.3);
PVector b = new PVector(-4, 0.5);
println(a + " " + b);
println(PVector.add(a, b) + " " + PVector.sub(a, b) + " " + PVector.mult(a, 0.3) + " " + PVector.div(a, 3));
PVector t = new PVector();
PVector.sub(a, b, t);
println(t);
println(a.mag() + " " + a.magSq() + " " + a.dot(b) + " " + a.dot(1, 2, 3) + " " + PVector.dot(a, b));
println(a.cross(b) + " " + PVector.cross(a, b, null));
println(a.dist(b) + " " + PVector.dist(a, b));
println(b.heading() + " " + a.heading() + " " + PVector.angleBetween(a, b) + " " + PVector.angleBetween(a, a));
PVector f = PVector.fromAngle(0.7);
println(f + " " + f.mag());
PVector r = new PVector(3, 4);
r.rotate(HALF_PI / 3);
println(r);
println(new PVector(1, 1).lerp(new PVector(5, 9), 0.25) + " " + PVector.lerp(a, b, 0.6) + " " + new PVector(0, 0, 0).lerp(10, 20, 30, 0.1));
PVector n = new PVector(3, 4, 12);
println(n.copy().normalize() + " " + n.copy().setMag(2) + " " + n.copy().limit(5) + " " + n.get());
PVector n2 = new PVector();
println(PVector.mult(n, 2, n2) + " " + n2 + " " + n.normalize(null));
println(new PVector(5, 0).setHeading(1.2));
float[] arr = a.array();
println(arr.length + " " + arr[0] + " " + arr[2]);
println(a.equals(new PVector(1.1, 2.2, 3.3)) + " " + a.equals(b) + " " + (a.hashCode() == new PVector(1.1, 2.2, 3.3).hashCode()));
PVector m = new PVector(2, 3, 4);
m.add(1, 1).sub(0.5, 0.5, 0.5).mult(1.5).div(2);
println(m + " " + m.x + " " + m.y + " " + m.z);
m.set(new float[] { 7, 8 });
println(m);
m.set(1, 2);
println(m);
println(new PVector(0.1f, 0.2f).add(new PVector(0.2f, 0.1f)).mag());
// The two-argument forms leave z alone.
PVector q = new PVector(1, 2, 3);
q.set(4, 5);
print(q + " ");
q.add(1, 1);
print(q + " ");
q.sub(2, 2);
println(q);
