// Library classes (Processing core + the parts of the JDK sketches use) for the type checker, read from
// api/library.gen.ts (generated by tools/manifest/generate.ts from the real jars).
//
// LibraryClassData: [name, flags, typeParams, superclass, interfaces, fields, constructors, methods]
//   name         binary name ("java.util.Map$Entry")
//   flags        see Flags in types.ts (1 static, 2 final, 4 abstract, 8 interface, 16 enum, 32 protected,
//                64 varargs, 128 default method, 256 annotation)
//   typeParams   "<K:Ljava.lang.Object;V:Ljava.lang.Object;>" or ""
//   superclass   signature or null; interfaces: signatures
//   fields       [name, signature, flags, constant?]
//   constructors [signature, flags]
//   methods      [name, signature, flags]
//   unavailable  names of public methods left out of the model (their signatures use classes outside it)
// Signatures follow the JVM generic signature grammar (JVMS 4.7.9.1) with "." as package separator;
// method signatures end with the thrown exceptions ("^Ljava.io.IOException;").
// Headers and members are parsed on first use of a class.
import { LIBRARY_DATA } from "./api/library.gen.ts";
import { ClassSymbol, Flags, T, classType, primType, setObjectType, type ClassType, type ConstValue, type MethodSymbol, type PrimName, type Type, type TypeVarSymbol } from "./types.ts";

type LibraryClassData = [string, number, string, string | null, string[], [string, string, number, ConstValue?][], [string, number][], [string, string, number][], string[]?];

const PRIMS: Record<string, PrimName | "void"> = { Z: "boolean", B: "byte", C: "char", S: "short", I: "int", J: "long", F: "float", D: "double", V: "void" };

export class Library {
  private readonly classes = new Map<string, ClassSymbol>();
  private readonly data = new Map<string, LibraryClassData>();
  /** package name → simple name → class (top-level classes only). */
  private readonly packages = new Map<string, Map<string, ClassSymbol>>();

  constructor(source: string = LIBRARY_DATA) {
    for (const d of JSON.parse(source) as LibraryClassData[]) this.data.set(d[0], d);
    for (const name of this.data.keys()) this.define(name);
    setObjectType(this.type("java.lang.Object"));
  }

  /** Class by binary name; unknown names become opaque classes (no members). */
  get(fullName: string): ClassSymbol {
    return this.classes.get(fullName) ?? this.define(fullName);
  }

  has(fullName: string): boolean {
    return this.data.has(fullName);
  }

  type(fullName: string, args: Type[] = []): ClassType {
    return classType(this.get(fullName), args);
  }

  /** Top-level classes of a package (for on-demand imports), or undefined if the package is unknown. */
  packageClasses(pkg: string): Map<string, ClassSymbol> | undefined {
    return this.packages.get(pkg);
  }

  /** True if some known class lives in this package or a subpackage of it. */
  isPackagePrefix(name: string): boolean {
    for (const p of this.packages.keys()) if (p === name || p.startsWith(name + ".")) return true;
    return false;
  }

  private define(fullName: string): ClassSymbol {
    const d = this.data.get(fullName);
    const dollar = fullName.lastIndexOf("$");
    const dot = fullName.lastIndexOf(".");
    const simple = fullName.slice(Math.max(dollar, dot) + 1);
    const sym = new ClassSymbol(fullName, simple, d ? d[1] : Flags.Opaque);
    this.classes.set(fullName, sym);
    if (dollar > dot) {
      const outer = this.get(fullName.slice(0, dollar));
      sym.outer = outer;
      outer.memberTypes.set(simple, sym);
      if (!(sym.flags & Flags.Static) && !sym.isInterface && !sym.isEnum) sym.flags |= Flags.Inner;
    } else {
      const pkg = fullName.slice(0, Math.max(dot, 0));
      let m = this.packages.get(pkg);
      if (!m) this.packages.set(pkg, (m = new Map()));
      m.set(simple, sym);
    }
    if (d) sym.loader = (c) => this.load(c, d);
    return sym;
  }

  private load(c: ClassSymbol, d: LibraryClassData) {
    const [, , typeParams, superclass, interfaces, fields, ctors, methods, unavailable] = d;
    if (unavailable) c.unavailableMethods = new Set(unavailable);
    const p = new SigParser(this, c.fullName);
    c.typeParams = p.typeParams(typeParams, c.fullName);
    const classVars = c.typeParams;
    if (superclass) c.superclass = p.classType(superclass, classVars);
    c.interfaces = interfaces.map((i) => p.classType(i, classVars));
    for (const [name, sig, flags, constant] of fields) {
      const type = p.type(sig, classVars);
      let value = constant;
      if (typeof value === "string" && type.tag === "prim") value = Number(value); // "Infinity", "NaN"
      if (typeof value === "number" && type.tag === "prim" && type.name === "boolean") value = value !== 0;
      // Floats are written the way Java prints them ("3.1415927"): round back to the float value.
      if (typeof value === "number" && type.tag === "prim" && type.name === "float") value = Math.fround(value);
      c.fields.set(name, { kind: "field", name, type, flags, owner: c, ...(value !== undefined ? { constant: value } : {}) });
    }
    for (const [sig, flags] of ctors) c.constructors.push(p.method("<init>", sig, flags, c, classVars));
    for (const [name, sig, flags] of methods) c.addMethod(p.method(name, sig, flags, c, classVars));
  }
}

/** Parser for one signature string at a time. */
class SigParser {
  private s = "";
  private i = 0;
  private readonly lib: Library;
  private readonly owner: string;

  constructor(lib: Library, owner: string) {
    this.lib = lib;
    this.owner = owner;
  }

  typeParams(sig: string, owner: string, outer: TypeVarSymbol[] = []): TypeVarSymbol[] {
    if (!sig) return [];
    this.s = sig;
    this.i = 0;
    return this.readTypeParams(owner, outer);
  }

  type(sig: string, vars: TypeVarSymbol[]): Type {
    this.s = sig;
    this.i = 0;
    return this.readType(vars);
  }

  classType(sig: string, vars: TypeVarSymbol[]): ClassType {
    const t = this.type(sig, vars);
    return t.tag === "class" ? t : this.lib.type("java.lang.Object");
  }

  method(name: string, sig: string, flags: number, owner: ClassSymbol, classVars: TypeVarSymbol[]): MethodSymbol {
    this.s = sig;
    this.i = 0;
    const typeParams = this.s[0] === "<" ? this.readTypeParams(`${owner.name}.${name}`, classVars) : [];
    const vars = typeParams.length ? [...typeParams, ...classVars] : classVars;
    this.i++; // (
    const params: Type[] = [];
    while (this.s[this.i] !== ")") params.push(this.readType(vars));
    this.i++;
    const ret = this.readType(vars);
    const m: MethodSymbol = { kind: "method", name, typeParams, params, ret, flags, owner };
    while (this.s[this.i] === "^") {
      this.i++;
      (m.throws ??= []).push(this.readType(vars));
    }
    return m;
  }

  private readTypeParams(owner: string, outer: TypeVarSymbol[]): TypeVarSymbol[] {
    this.i++; // <
    const out: TypeVarSymbol[] = [];
    const pending: { sym: TypeVarSymbol; at: number[] }[] = [];
    // Bounds may refer to later parameters (<T extends Comparable<T>>): read names first, bounds after.
    while (this.s[this.i] !== ">") {
      const colon = this.s.indexOf(":", this.i);
      const sym: TypeVarSymbol = { kind: "tvar", name: this.s.slice(this.i, colon), bounds: [], owner };
      out.push(sym);
      this.i = colon;
      const at: number[] = [];
      while (this.s[this.i] === ":") {
        this.i++;
        if (this.s[this.i] === ":") continue; // empty class bound
        at.push(this.i);
        this.skipType();
      }
      pending.push({ sym, at });
    }
    const end = this.i + 1;
    const vars = [...out, ...outer];
    for (const p of pending) {
      for (const at of p.at) {
        this.i = at;
        p.sym.bounds.push(this.readType(vars));
      }
    }
    this.i = end;
    return out;
  }

  private skipType() {
    const c = this.s[this.i];
    if (c === "[") {
      this.i++;
      this.skipType();
    } else if (c === "L" || c === "T") {
      let depth = 0;
      for (; this.i < this.s.length; this.i++) {
        const ch = this.s[this.i];
        if (ch === "<") depth++;
        else if (ch === ">") depth--;
        else if (ch === ";" && depth === 0) break;
      }
      this.i++;
    } else this.i++;
  }

  private readType(vars: TypeVarSymbol[]): Type {
    const c = this.s[this.i++];
    switch (c) {
      case "[": return { tag: "array", elem: this.readType(vars) };
      case "T": {
        const end = this.s.indexOf(";", this.i);
        const name = this.s.slice(this.i, end);
        this.i = end + 1;
        const v = vars.find((x) => x.name === name);
        return v ? { tag: "tvar", sym: v } : T.error;
      }
      case "L": {
        let j = this.i;
        while (this.s[j] !== "<" && this.s[j] !== ";") j++;
        const name = this.s.slice(this.i, j);
        this.i = j;
        const args: Type[] = [];
        if (this.s[this.i] === "<") {
          this.i++;
          while (this.s[this.i] !== ">") args.push(this.readTypeArg(vars));
          this.i++;
        }
        this.i++; // ;
        return classType(this.lib.get(name), args);
      }
      case "*": return { tag: "wild", bound: null, upper: true };
      default: {
        const p = PRIMS[c];
        if (!p) throw new Error(`Bad signature in ${this.owner}: ${this.s}`);
        return p === "void" ? T.void : primType(p);
      }
    }
  }

  private readTypeArg(vars: TypeVarSymbol[]): Type {
    const c = this.s[this.i];
    if (c === "*") {
      this.i++;
      return { tag: "wild", bound: null, upper: true };
    }
    if (c === "+" || c === "-") {
      this.i++;
      return { tag: "wild", bound: this.readType(vars), upper: c === "+" };
    }
    return this.readType(vars);
  }
}
