#!/usr/bin/env node
// Generate src/compiler/api/processing-core.json (API listing) and src/compiler/api/library.gen.ts (compact
// model for the type checker, including parts of the JDK) from the installed Processing by reflection.
// Usage: node tools/manifest/generate.ts [--processing <Processing executable>]
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { parseArgs } from "node:util";
import { findProcessing } from "../vt/processing.ts";

const ROOT = path.resolve(import.meta.dirname, "../..");
const OUT = path.join(ROOT, "src/compiler/api/processing-core.json");
const LIBRARY_OUT = path.join(ROOT, "src/compiler/api/library.gen.ts");

const { values: flags } = parseArgs({ options: { processing: { type: "string" } } });
const exe = findProcessing(flags.processing);
if (!exe) {
  console.error("Processing not found (--processing <path> or PROCESSING_PATH).");
  process.exit(2);
}
const install = path.dirname(exe);
const appDir = path.join(install, "app");
const jdkBin = path.join(appDir, "resources/jdk/bin");
const java = path.join(jdkBin, process.platform === "win32" ? "java.exe" : "java");
const javac = path.join(jdkBin, process.platform === "win32" ? "javac.exe" : "javac");
for (const p of [java, javac]) if (!fs.existsSync(p)) throw new Error(`JDK tool not found: ${p}`);

// core + JOGL/gluegen (PShader & co. reference JOGL types in their signatures).
const jars = fs.readdirSync(appDir).filter((f) => /^(core|jogl-all|gluegen-rt)-[\d.]+(-[0-9a-f]+)?\.jar$/.test(f)).map((f) => path.join(appDir, f));
const core = jars.find((j) => path.basename(j).startsWith("core-"));
if (!core) throw new Error(`core jar not found in ${appDir}`);
const version = path.basename(core).match(/^core-([\d.]+)/)![1];

const work = fs.mkdtempSync(path.join(os.tmpdir(), "pts-manifest-"));
const cp = [...jars, work].join(path.delimiter);
execFileSync(javac, ["-cp", jars.join(path.delimiter), "-d", work, path.join(import.meta.dirname, "ManifestGen.java")], { stdio: "inherit" });
const json = execFileSync(java, ["-cp", cp, "ManifestGen"], { encoding: "utf8", maxBuffer: 1 << 26 });
const library = execFileSync(java, ["-cp", cp, "ManifestGen", "library"], { encoding: "utf8", maxBuffer: 1 << 26 });
fs.rmSync(work, { recursive: true, force: true });

// Compact model for the compiler (src/compiler/api/library.ts reads it). JSON.parse of a string is
// faster to load than the equivalent object literal.
const libClasses = pruneLibrary(JSON.parse(library) as LibClass[]);
fs.writeFileSync(LIBRARY_OUT, [
  "// Generated by tools/manifest/generate.ts from Processing " + version + " (core jar and its bundled JDK). Do not edit.",
  "// Format: see LibraryClassData in ./library.ts.",
  `export const LIBRARY_VERSION = ${JSON.stringify(version)};`,
  `export const LIBRARY_DATA: string = ${JSON.stringify(JSON.stringify(libClasses))};`,
  "",
].join("\n"));
console.log(`wrote ${path.relative(ROOT, LIBRARY_OUT)} (${libClasses.length} classes, ${(fs.statSync(LIBRARY_OUT).size / 1024).toFixed(0)} KiB)`);

const manifest = JSON.parse(json) as { classes: { name: string; methods: { name: string }[]; fields: unknown[] }[] };
const result = { processing: version, generatedBy: "tools/manifest/generate.ts", ...manifest };
fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, compactJson(result) + "\n");

for (const c of manifest.classes) {
  const names = new Set(c.methods.map((m) => m.name));
  console.log(`${c.name.padEnd(36)} methods ${String(names.size).padStart(4)} names / ${String(c.methods.length).padStart(4)} overloads, fields ${c.fields.length}`);
}
console.log(`\nwrote ${path.relative(ROOT, OUT)} (Processing ${version})`);

type LibClass = [string, number, string, string | null, string[], [string, string, number, unknown?][], [string, number][], [string, string, number][], string[]?];

/**
 * Keep the model small: members whose signatures mention classes outside the model cannot be used in
 * processing-ts anyway, and protected members only matter for PApplet (the sketch's superclass).
 * The names of dropped public methods are kept (9th element) so the checker can say they are not
 * available instead of not existing.
 */
function pruneLibrary(classes: LibClass[]): LibClass[] {
  const known = new Set(classes.map((c) => c[0]));
  const ok = (sig: string) => [...sig.matchAll(/L([\w.$]+)[<;]/g)].every((m) => known.has(m[1]));
  const keepProtected = new Set(["processing.core.PApplet", "java.lang.Object"]);
  let removed = 0;
  const out = classes.map((c): LibClass => {
    const prot = keepProtected.has(c[0]);
    const keep = (sig: string, flags: number) => (prot || !(flags & 32)) && ok(sig);
    const fields = c[5].filter((f) => keep(f[1], f[2]));
    const ctors = c[6].filter((k) => keep(k[0], k[1]));
    const methods = c[7].filter((m) => keep(m[1], m[2]));
    removed += c[5].length - fields.length + c[6].length - ctors.length + c[7].length - methods.length;
    const kept = new Set(methods.map((m) => m[0]));
    const unavailable = [...new Set(c[7].filter((m) => !(m[2] & 32) && !kept.has(m[0])).map((m) => m[0]))];
    return unavailable.length ? [c[0], c[1], c[2], c[3], c[4], fields, ctors, methods, unavailable] : [c[0], c[1], c[2], c[3], c[4], fields, ctors, methods];
  });
  console.log(`library: ${removed} members dropped (protected outside PApplet, or referring to classes outside the model)`);
  return out;
}

/** Pretty-print the outer levels and keep each field/constructor/method on one line (readable diffs, smaller file). */
function compactJson(value: unknown, depth = 0): string {
  const pad = "  ".repeat(depth);
  if (depth >= 4 || value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) {
    if (value.length === 0 || value.every((v) => typeof v !== "object")) return JSON.stringify(value);
    return "[\n" + value.map((v) => pad + "  " + compactJson(v, depth + 1)).join(",\n") + "\n" + pad + "]";
  }
  const entries = Object.entries(value as Record<string, unknown>);
  return "{\n" + entries.map(([k, v]) => `${pad}  ${JSON.stringify(k)}: ${compactJson(v, depth + 1)}`).join(",\n") + "\n" + pad + "}";
}
